#! /bin/sh

if [ $# -eq 2 ]; then
  git clone https://github.com/$1/$2.git
elif [ $# -eq 3 ]; then
  git clone https://github.com/$1/$2.git $3
else
  echo 'gh-clone: usage: \033[1mgh-clone\033[0m \033[3mowner repository\033[0m [\033[3mdestination\033[0m]'
fi
