#! /bin/sh

CONFDIR=/home/$USER/.config
CONFFILE=$CONFDIR/serve.nginx.conf
if ! [ -f $CONFFILE ]; then
  mkdir -p $CONFDIR
  cat <<EOF > $CONFFILE
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        add_header Cache-Control 'no-store, no-cache';
        expires off;
        etag off;
    }
}
EOF
fi

docker run --rm -p 8888:80 -v $PWD:/usr/share/nginx/html:ro -v $CONFFILE:/etc/nginx/conf.d/default.conf nginx
